server:
  port: 8081
  servlet:
    context-path: /re
    session:
      cookie:
       # token有效期 432000毫秒 12小时
        max-age: 43200000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/react-admin?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    mode: HTML5
mybatis:
  mapper-locations: classpath:mybatis/*.xml
logging:
  config: classpath:logback-spring.xml